$(document).ready(function(){
	$("#work1").hover(function(){
    $('#aw1').toggleClass('visible');
},function(){
    $('#aw1').removeClass('visible');
	});
	$("#work2").hover(function(){
    $('#aw2').toggleClass('visible');
},function(){
    $('#aw2').removeClass('visible');
	});
	$("#work3").hover(function(){
    $('#aw3').toggleClass('visible');
},function(){
    $('#aw3').removeClass('visible');
	});
	$("#work4").hover(function(){
    $('#aw4').toggleClass('visible');
},function(){
    $('#aw4').removeClass('visible');
	});
});



$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})
});

$(document).ready(function(){
	$(".article-info").click(function(event){
		event.preventDefault();
		$(this).click(function(){
			$(".article").toggleClass("ok");
		})
	})
})